### ISSUE TITLE
Temporal Dependencies can not be specified without fields

### ISSUE THREAD

**Issue by sanishmahadik** [srohatgi/graph#8]
If I want to say A should happen before B, but B does not depend on the output of A, there is no way to specify this.

One needs to specify fromfield and tofield as well.

```
dependencies:
    - fromresource: maestro-search-cfn
      fromfield: SHIAMRoleARN
      tofield: IAMRoleARN
```

Remove this requirement.
