### ISSUE TITLE
wrong resourceName in dependencies fromResource leads to panic

### ISSUE THREAD

**Issue by melugoyal** [srohatgi/graph#9]
this can be reproed by changing spec and override spec in example_usage.go to the following:

```
const spec = `
kinesis:
- name: mykin2
  shardcount: 5
  streamname: myEventStream
deployment:
- name: mydep
  dependencies:
  - fromresource: mykin
    fromfield: Arn
    tofield: KinesisArn
dynamo:
- name: mydyn
  tablename: myDynamoTable
`

const overrideSpec = `
kinesis2:
- name: mykin2
  shardcount: 10
`
```

stack trace:
```
panic: reflect: call of reflect.Value.Elem on zero Value [recovered]
	panic: reflect: call of reflect.Value.Elem on zero Value

goroutine 1 [running]:
testing.runExample.func2(0xbf1f59ffb90317c0, 0x584079, 0x12a8cc0, 0xc00000c070, 0xc00000c018, 0xc0000707e0, 0x1189dd3, 0xd, 0x1193930, 0x119344d, ...)
	/usr/local/Cellar/go/1.11.5/libexec/src/testing/example.go:116 +0x6f8
panic(0x115c700, 0xc00000aa40)
	/usr/local/Cellar/go/1.11.5/libexec/src/runtime/panic.go:513 +0x1b9
reflect.Value.Elem(0x0, 0x0, 0x0, 0xc000016900, 0xa, 0x1151300)
	/usr/local/Cellar/go/1.11.5/libexec/src/reflect/value.go:805 +0x1bd
github.com/srohatgi/graph.checkField(0x0, 0x0, 0xc0000168e8, 0x3, 0x12c5900, 0x0)
	/Users/mehulg/go/src/github.com/srohatgi/graph/builder.go:150 +0xea
github.com/srohatgi/graph.check(0xc00000aa20, 0x2, 0x2, 0xc00000ee40, 0xc000095ac0)
	/Users/mehulg/go/src/github.com/srohatgi/graph/builder.go:136 +0x4ce
github.com/srohatgi/graph.Sync(0x11b1960, 0xc00000ee40, 0xc00000aa20, 0x2, 0x2, 0xc00000ee00, 0x11b1960, 0xc00000ee40, 0xc000095b48)
	/Users/mehulg/go/src/github.com/srohatgi/graph/builder.go:95 +0x46
github.com/srohatgi/graph_test.Example_usage()
	/Users/mehulg/go/src/github.com/srohatgi/graph/example_test.go:114 +0x289
testing.runExample(0x1189dd3, 0xd, 0x1193930, 0x119344d, 0x94, 0x0, 0x0)
	/usr/local/Cellar/go/1.11.5/libexec/src/testing/example.go:121 +0x1fd
testing.runExamples(0xc000095ef0, 0x12a1aa0, 0x1, 0x1, 0x1000101)
	/usr/local/Cellar/go/1.11.5/libexec/src/testing/example.go:45 +0x1ad
testing.(*M).Run(0xc0000b4080, 0x0)
	/usr/local/Cellar/go/1.11.5/libexec/src/testing/testing.go:1035 +0x1fb
main.main()
	_testmain.go:66 +0x13d
FAIL	github.com/srohatgi/graph	0.022s
```

stack trace is from v0.5.1
